# AI Disclosure: This entire script was generated by Gemini 2.5 Pro
import sys
import boto3
from botocore.exceptions import ClientError


def format_size(size_bytes):
    """Converts a size in bytes to a human-readable format (KB, MB, GB, etc.)."""
    if size_bytes == 0:
        return "0 B"
    power = 1024
    n = 0
    power_labels = {0: '', 1: 'K', 2: 'M', 3: 'G', 4: 'T'}
    while size_bytes >= power and n < len(power_labels):
        size_bytes /= power
        n += 1
    return f"{size_bytes:.2f} {power_labels[n]}B"


def find_latest_year_for_state(bucket_name, state_prefix):
    """
    Finds the latest year available for a given state by listing common prefixes.
    """
    s3_client = boto3.client('s3')
    print(f"🔎 Discovering latest year for state '{state_prefix.upper()}'...")
    try:
        # The Delimiter argument groups common prefixes, simulating folders.
        response = s3_client.list_objects_v2(
            Bucket=bucket_name,
            Prefix=f"{state_prefix.lower()}/",
            Delimiter='/',
            RequestPayer='requester'
        )
    except ClientError as e:
        print(f"❌ AWS Error: {e}. Check if the bucket name and state are correct.")
        return None

    if 'CommonPrefixes' not in response:
        print(f"❌ No year folders found for state '{state_prefix}'. Please check the state abbreviation.")
        return None

    # Extract year from prefixes like 'nc/2023/'
    years = [int(p.get('Prefix').split('/')[-2]) for p in response['CommonPrefixes'] if
             p.get('Prefix').split('/')[-2].isdigit()]

    if not years:
        print(f"Could not determine latest year for state '{state_prefix}'.")
        return None

    latest_year = max(years)
    print(f"✅ Latest year found: {latest_year}")
    return latest_year


def get_folder_size_for_year(bucket_name, state_prefix, year):
    """
    Calculates the total size and object count for a specific state and year
    in a "requester pays" S3 bucket.
    """
    s3_client = boto3.client('s3')
    paginator = s3_client.get_paginator('list_objects_v2')

    total_size_bytes = 0
    total_objects = 0

    # Construct the full prefix for the specific state and year
    folder_prefix = f"{state_prefix.lower()}/{year}/"

    print(f"\n🔎 Calculating size for path 's3://{bucket_name}/{folder_prefix}'...")
    print("(This can take several minutes depending on the number of files)")

    try:
        pages = paginator.paginate(
            Bucket=bucket_name,
            Prefix=folder_prefix,
            RequestPayer='requester'
        )

        for page in pages:
            if 'Contents' in page:
                for obj in page['Contents']:
                    total_size_bytes += obj['Size']
                    total_objects += 1

        print("\n✅ Calculation Complete!")
        print("-----------------------------------")
        print(f" State / Year:      {state_prefix.upper()} / {year}")
        print(f" Total Objects Found: {total_objects:,}")
        print(f" Total Size (Human):  {format_size(total_size_bytes)}")
        print("-----------------------------------")

    except ClientError as e:
        if e.response['Error']['Code'] == 'NoSuchBucket':
            print(f"❌ Error: The bucket '{bucket_name}' does not exist.")
        elif e.response['Error']['Code'] == 'AccessDenied':
            print("❌ Error: Access Denied. Check your AWS credentials and permissions.")
        else:
            print(f"❌ An unexpected AWS error occurred: {e}")
    except Exception as e:
        print(f"❌ An unexpected error occurred: {e}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python get_latest_state_size.py <bucket_name> <state_abbreviation>")
        print("Example: python get_latest_state_size.py naip-source nc")
        sys.exit(1)

    bucket = sys.argv[1]
    state = sys.argv[2]

    # First, find the latest year
    latest_year = find_latest_year_for_state(bucket, state)

    # If a year was found, proceed to calculate the size for that year
    if latest_year:
        get_folder_size_for_year(bucket, state, latest_year)
